export default {
  base: {
    name: 'Cơ bản',
    children: [
      {
        title: 'Loại nguồn',
        id: 'bookSourceType',
        type: 'Array',
        array: ['Văn bản', 'Âm thanh', 'Hình ảnh', 'Tệp tin'],
        required: true,
      },
      {
        title: 'Tên miền nguồn',
        id: 'bookSourceUrl',
        type: 'String',
        hint: 'Thường là trang chủ, ví dụ: https://www.qidian.com',
        required: true,
      },
      {
        title: 'Tên nguồn',
        id: 'bookSourceName',
        type: 'String',
        hint: 'Hiển thị trong danh sách nguồn',
        required: true,
      },
      {
        title: 'Nhóm nguồn',
        id: 'bookSourceGroup',
        type: 'String',
        hint: 'Thông tin phân loại nguồn',
      },
      {
        title: 'Ghi chú',
        id: 'bookSourceComment',
        type: 'String',
        hint: 'Tác giả và trạng thái nguồn',
      },
      {
        title: 'URL Đăng nhập',
        id: 'loginUrl',
        type: 'String',
        hint: 'Điền URL đăng nhập, chỉ dùng khi nguồn cần đăng nhập',
      },
      {
        title: 'Giao diện Đăng nhập',
        id: 'loginUi',
        type: 'String',
        hint: 'Giao diện đăng nhập tùy chỉnh',
      },
      {
        title: 'Kiểm tra Đăng nhập',
        id: 'loginCheckJs',
        type: 'String',
        hint: 'JS kiểm tra đăng nhập',
      },
      {
        title: 'Giải mã Bìa',
        id: 'coverDecodeJs',
        type: 'String',
        hint: 'JS giải mã ảnh bìa',
      },
      {
        title: 'Xác thực Link',
        id: 'bookUrlPattern',
        type: 'String',
        hint: 'Regex URL sách, dùng khi URL trang chi tiết và URL nguồn khác tên miền',
      },
      {
        title: 'Header',
        id: 'header',
        type: 'String',
        hint: 'Nhận diện User-Agent',
      },
      {
        title: 'Biến tùy chỉnh',
        id: 'variableComment',
        type: 'String',
        hint: 'Mô tả biến nguồn sách',
      },
      {
        title: 'Tỷ lệ đồng thời',
        id: 'concurrentRate',
        type: 'String',
        hint: 'Tốc độ, vd: 1000 (cách nhau 1000ms) hoặc 1/1000 (1 lần trong 1000ms)',
      },
      {
        title: 'Thư viện JS',
        id: 'jsLib',
        type: 'String',
        hint: 'Thư viện JS, có thể điền JS hoặc object key-value để tải online',
      },
    ],
  },
  search: {
    name: 'Tìm kiếm',
    children: [
      {
        title: 'URL Tìm kiếm',
        id: 'searchUrl',
        type: 'String',
        hint: '[Tên miền có thể bỏ qua]/search.php@kw={{key}}',
      },
      {
        title: 'Từ khóa kiểm tra',
        namespace: 'ruleSearch',
        id: 'checkKeyWord',
        type: 'String',
        hint: 'Từ khóa để kiểm tra, rất khuyến nghị điền',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleSearch',
        id: 'bookList',
        type: 'String',
        hint: 'Chọn node sách (Kết quả là List<Element>)',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleSearch',
        id: 'name',
        type: 'String',
        hint: 'Chọn node tên sách (Kết quả là String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleSearch',
        id: 'author',
        type: 'String',
        hint: 'Chọn node tác giả (Kết quả là String)',
      },
      {
        title: 'Quy tắc thể loại',
        namespace: 'ruleSearch',
        id: 'kind',
        type: 'String',
        hint: 'Chọn node thể loại (Kết quả là String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleSearch',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn node số chữ (Kết quả là String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleSearch',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn node chương mới nhất (Kết quả là String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleSearch',
        id: 'intro',
        type: 'String',
        hint: 'Chọn node giới thiệu (Kết quả là String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleSearch',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn node ảnh bìa (Kết quả là URL String)',
      },
      {
        title: 'URL chi tiết',
        namespace: 'ruleSearch',
        id: 'bookUrl',
        type: 'String',
        hint: 'Chọn URL trang chi tiết (Kết quả là URL String)',
      },
    ],
  },
  find: {
    name: 'Khám phá',
    children: [
      {
        title: 'URL Khám phá',
        id: 'exploreUrl',
        type: 'String',
        hint: 'Định dạng từng mục <tên>::<url> hoặc {url:<url>,title:<tên>,style:...}; dùng xuống dòng hoặc && để nối, dùng JS tạo động cũng được',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleExplore',
        id: 'bookList',
        type: 'String',
        hint: 'Chọn node sách (Kết quả là List<Element>)',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleExplore',
        id: 'name',
        type: 'String',
        hint: 'Chọn node tên sách (Kết quả là String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleExplore',
        id: 'author',
        type: 'String',
        hint: 'Chọn node tác giả (Kết quả là String)',
      },
      {
        title: 'Quy tắc thể loại',
        namespace: 'ruleExplore',
        id: 'kind',
        type: 'String',
        hint: 'Chọn node thể loại (Kết quả là String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleExplore',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn node số chữ (Kết quả là String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleExplore',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn node chương mới nhất (Kết quả là String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleExplore',
        id: 'intro',
        type: 'String',
        hint: 'Chọn node giới thiệu (Kết quả là String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleExplore',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn node ảnh bìa (Kết quả là URL String)',
      },
      {
        title: 'URL chi tiết',
        namespace: 'ruleExplore',
        id: 'bookUrl',
        type: 'String',
        hint: 'Chọn URL trang chi tiết (Kết quả là URL String)',
      },
    ],
  },
  detail: {
    name: 'Chi tiết',
    children: [
      {
        title: 'Tiền xử lý',
        namespace: 'ruleBookInfo',
        id: 'init',
        type: 'String',
        hint: 'Tăng tốc lấy thông tin chi tiết, chỉ hỗ trợ quy tắc AllInOne',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleBookInfo',
        id: 'name',
        type: 'String',
        hint: 'Chọn node tên sách (Kết quả là String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleBookInfo',
        id: 'author',
        type: 'String',
        hint: 'Chọn node tác giả (Kết quả là String)',
      },
      {
        title: 'Quy tắc thể loại',
        namespace: 'ruleBookInfo',
        id: 'kind',
        type: 'String',
        hint: 'Chọn node thể loại (Kết quả là String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleBookInfo',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn node số chữ (Kết quả là String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleBookInfo',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn node chương mới nhất (Kết quả là String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleBookInfo',
        id: 'intro',
        type: 'String',
        hint: 'Chọn node giới thiệu (Kết quả là String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleBookInfo',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn node ảnh bìa (Kết quả là URL String)',
      },
      {
        title: 'URL Mục lục',
        namespace: 'ruleBookInfo',
        id: 'tocUrl',
        type: 'String',
        hint: 'Chọn URL mục lục (Kết quả là URL String, bỏ trống nếu giống trang chi tiết)',
      },
      {
        title: 'Sửa thông tin',
        namespace: 'ruleBookInfo',
        id: 'canReName',
        type: 'String',
        hint: 'Cho phép sửa tên/tác giả (Kết quả Bool, mặc định không)',
      },
      {
        title: 'URL Tải về',
        namespace: 'ruleBookInfo',
        id: 'downloadUrls',
        type: 'String',
        hint: 'URL tải về cho nguồn file (Kết quả URL String, nhiều link trả về mảng)',
      },
    ],
  },
  directory: {
    name: 'Mục lục',
    children: [
      {
        title: 'JS trước cập nhật',
        namespace: 'ruleToc',
        id: 'preUpdateJs',
        type: 'String',
        hint: 'JS chạy trước khi cập nhật để lấy link mục lục động',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleToc',
        id: 'chapterList',
        type: 'String',
        hint: 'Chọn node chương trong danh sách (Kết quả là List<Element>)',
      },
      {
        title: 'Tên chương',
        namespace: 'ruleToc',
        id: 'chapterName',
        type: 'String',
        hint: 'Chọn tên chương (Kết quả là String)',
      },
      {
        title: 'URL Chương',
        namespace: 'ruleToc',
        id: 'chapterUrl',
        type: 'String',
        hint: 'Chọn link chương (Kết quả là URL String)',
      },
      {
        title: 'Xử lý tiêu đề',
        namespace: 'ruleToc',
        id: 'formatJs',
        type: 'String',
        hint: 'JS callback sau khi lọc trùng, có biến index, title. Trả về tiêu đề mới',
      },
      {
        title: 'Là tên tập',
        namespace: 'ruleToc',
        id: 'isVolume',
        type: 'String',
        hint: 'Tên chương này là tên tập/quyển (Kết quả Bool)',
      },
      {
        title: 'Thông tin chương',
        namespace: 'ruleToc',
        id: 'updateTime',
        type: 'String',
        hint: 'Thông tin bổ sung như thời gian cập nhật (Kết quả String)',
      },
      {
        title: 'Chương VIP',
        namespace: 'ruleToc',
        id: 'isVip',
        type: 'String',
        hint: 'Chương này là VIP (Kết quả Bool)',
      },
      {
        title: 'Đã mua',
        namespace: 'ruleToc',
        id: 'isPay',
        type: 'String',
        hint: 'Chương này đã mua (Kết quả Bool)',
      },
      {
        title: 'URL Trang sau',
        namespace: 'ruleToc',
        id: 'nextTocUrl',
        type: 'String',
        hint: 'Link trang mục lục tiếp theo (List<String> hoặc String)',
      },
    ],
  },
  content: {
    name: 'Nội dung',
    children: [
      {
        title: 'Nội dung chính',
        namespace: 'ruleContent',
        id: 'content',
        type: 'String',
        hint: 'Chọn nội dung chính (Kết quả là String)',
      },
      {
        title: 'Tiêu đề',
        namespace: 'ruleContent',
        id: 'title',
        type: 'String',
        hint: 'Ghi đè tiêu đề chương (Kết quả là String)',
      },
      {
        title: 'Trang sau',
        namespace: 'ruleContent',
        id: 'nextContentUrl',
        type: 'String',
        hint: 'Link phân trang nội dung (không phải chương sau) (URL String)',
      },
      {
        title: 'Inject JS',
        namespace: 'ruleContent',
        id: 'webJs',
        type: 'String',
        hint: 'JS chạy mô phỏng click, v.v. Phải trả về String',
      },
      {
        title: 'Regex Tài nguyên',
        namespace: 'ruleContent',
        id: 'sourceRegex',
        type: 'String',
        hint: 'Regex để sniff tài nguyên media',
      },
      {
        title: 'Regex Thay thế',
        namespace: 'ruleContent',
        id: 'replaceRegex',
        type: 'String',
        hint: 'Thay thế nội dung sau khi gộp trang, dùng để lọc rác',
      },
      {
        title: 'Kiểu ảnh',
        namespace: 'ruleContent',
        id: 'imageStyle',
        type: 'String',
        hint: 'FULL: Tràn màn hình. Bỏ trống: Mặc định',
      },
      {
        title: 'Giải mã ảnh',
        namespace: 'ruleContent',
        id: 'imageDecode',
        type: 'String',
        hint: 'JS trả về bytes của ảnh đã giải mã',
      },
      {
        title: 'Hành động mua',
        namespace: 'ruleContent',
        id: 'payAction',
        type: 'String',
        hint: 'JS trả về link mua hoặc gọi API mua',
      },
    ],
  },
  /*
  review: {
    name: "段评",
    children: [
      {
        title: "段评URL",
        namespace: "ruleReview",
id: "reviewUrl",
        type: "String",
        hint: "段评URL",
      },
      {
        title: "发布头像",
        namespace: "ruleReview",
id: "avatarRule",
        type: "String",
        hint: "段评发布者头像",
      },
      {
        title: "段评内容",
        namespace: "ruleReview",
id: "contentRule",
        type: "String",
        hint: "段评内容",
      },
      {
        title: "发布时间",
        namespace: "ruleReview",
id: "postTimeRule",
        type: "String",
        hint: "段评发布时间",
      },
      {
        title: "回复URL",
        namespace: "ruleReview",
id: "reviewQuoteUrl",
        type: "String",
        hint: "获取段评回复URL",
      },
      {
        title: "点赞URL",
        namespace: "ruleReview",
id: "voteUpUrl",
        type: "String",
        hint: "点赞URL",
      },
      {
        title: "点踩URL",
        namespace: "ruleReview",
id: "voteDownUrl",
        type: "String",
        hint: "点踩URL",
      },
      {
        title: "发送回复",
        namespace: "ruleReview",
id: "postReviewUrl",
        type: "String",
        hint: "发送回复URL",
      },
      {
        title: "回复段评",
        namespace: "ruleReview",
id: "postQuoteUrl",
        type: "String",
        hint: "发送回复段评URL",
      },
      {
        title: "删除段评",
        namespace: "ruleReview",
id: "deleteUrl",
        type: "String",
        hint: "删除段评URL",
      },
    ],
  },*/
  other: {
    name: 'Khác',
    children: [
      {
        title: 'Bật Tìm kiếm',
        id: 'enabled',
        type: 'Boolean',
      },
      {
        title: 'Bật Khám phá',
        id: 'enabledExplore',
        type: 'Boolean',
      },
      // {
      //   title: "启用段评",
      //   id: "enabledReview",
      //   type: "Boolean",
      // },
      {
        title: 'CookieJar',
        id: 'enabledCookieJar',
        type: 'Boolean',
      },
      {
        title: 'Ưu tiên',
        id: 'weight',
        type: 'Number',
      },
      {
        title: 'Thứ tự',
        id: 'customOrder',
        type: 'Number',
      },
    ],
  },
}
